[colors.primary]
background = '#300a24'
foreground = '#ffffff'

[colors.normal]
black   = '#171421'
red     = '#c01c28'
green   = '#26a269'
yellow  = '#a2734c'
blue    = '#12488b'
magenta = '#a347ba'
cyan    = '#2aa1b3'
white   = '#d0cfcc'

[colors.bright]
black   = '#5e5c64'
red     = '#f66151'
green   = '#33d17a'
yellow  = '#e9ad0c'
blue    = '#2a7bde'
magenta = '#c061cb'
cyan    = '#33c7de'
white   = '#ffffff'

[window.dimensions]
columns = 120
lines = 36

[font]
size = 14.0

[font.normal]
family = "DejaVuSansM Nerd Font Mono"

[keyboard]
bindings = [
    { key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
]